export default {
  categoryIndex: 0,
  spotCategories: [],
  categoriesIcon: [],
  wxCenter: [30.152991,119.984647],
  locationName: "杭州野生动物世界",
  locationAddress: "浙江省杭州市富阳区杭富路九龙大道1号",
  spotsData: [],
  lineSpotsData: {},
  query: "",
  audioUrl: "",
  audioPlaying: false,
  paths: [],
  splitPaths: [],
  endMarkerName: "",
  distance: 0,
  duration: 0,
  categoriesName: [],
  showRecommend: false,
  showCategories: true,
  searching: false,
  mapId: 0,
  mapIdList: [],
  spotDetail: {},
  searchSpots: "https://www.ipow.cn/HzspMapBaiduServices/spots.ashx",
  showInfo: "https://www.ipow.cn/HzspMapBaiduServices/ShowInfo.ashx",
  recommendroutes: "https://www.ipow.cn/HzspMapBaiduServices/recommendroutes.ashx",
  placeSearch: "https://www.ipow.cn/HzspMapBaiduServices/PlaceSearch.ashx",
  routePlanning: "https://www.ipow.cn/HzspMapBaiduServices/RoutePlanning.ashx",
  introduction: process.env.NODE_ENV == "production" ? "https://www.ipow.cn/HzspMapBaiduServices/api/scenic/Introduction" : "/Introduction"
}
